import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Project } from '../project';

@Injectable({
  providedIn: 'root'
})
export class ProjectService {
  private projectList:Project[]= [
    {
      id: 1,
      title: "IP Mobile Application",
      shortdescription:"Part of a group project involving multiple software components. ",
      description: "I developed this application as part of a more complex project. Our 8-person team created a real-time medical monitoring system. The main architectural components included a server, a database, sensors, a web application, and a mobile application. The system can handle multiple users with different roles, such as doctors, patients, and administrators. My role was to develop the mobile application, including both frontend and backend, which needed to communicate with the server. In addition to basic functions such as registration, login, and information display, the app features a nearly real-time chat.",
      image: "assets/projects/IP.png",
      link: "https://github.com/Titusz1928/IP_MobileAppFinal.git",
      maintag: "Mobile",
      tags: ["Java", "Android Studio", "Group","MySql","Arduino","Python","Flaks"],
      images: [],
      latestUpdate: new Date(2024, 5, 1),
    },
    {
      id: 2,
      title: "Syncretic project 2",
      shortdescription:"Control of Arduino board and circuit from a website",
      description: "Control of Arduino board and circuit from a website",
      image: "assets/projects/ps2.png",
      link: "https://github.com/Titusz1928/PS2N.git",
      maintag: "Web",
      tags: ["Java", "Python", "Flask", "Arduino", "C++"],
      images: [],
      latestUpdate: new Date(2024, 4, 21),
    },
    {
      id: 3,
      title: "TCP Network Project",
      shortdescription:"Multithreaded server capable of handling multiple clients, basic communication and commands",
      description: "Multithreaded server capable of handling multiple clients, basic communication and commands",
      image: "assets/projects/rc.png",
      link: "https://github.com/Titusz1928/Proiect-RC.git",
      maintag: "Networks",
      tags: ["C", "Linux", "TCP", "Concurrent Programming"],
      images: [],
      latestUpdate: new Date(2024, 3, 24),
    },
    {
      id: 4,
      title: "Chat Mobile Application",
      shortdescription:"",
      description: "Alternative version of IP Mobile App where i implemented a chat with http requests, its not really real time but acceptable, users can message with other users and the messages get stored in a database.",
      image: "assets/projects/IPa.png",
      link:'https://github.com/Titusz1928/IP_mobileApp.git',
      maintag: "Mobile",
      tags: ["Java", "Python", "Flask", "MySql"],
      images: [],
      latestUpdate: new Date(2024, 5, 1),
    },
    {
      id: 5,
      title: "Angular Application",
      shortdescription:"",
      description: "This is my first web application made with angular, I tested out a lot of things with it, I deployed it on Netify too so it needed to be static. You can see it here: https://dainty-begonia-a5dbd3.netlify.app/login",
      image: "assets/projects/ang1.png",
      link:'https://github.com/Titusz1928/hotelinventoryApp.git',
      maintag: "Web",
      tags: ["Angular", "Typescript"],
      images: [],
      latestUpdate: new Date(2024, 5, 25),
    },
    {
      id: 6,
      title: "Angular Personal Website",
      shortdescription:"",
      description: "The result of this project was the website that you are on right now",
      image: "assets/projects/ang2.png",
      link:'',
      maintag: "Web",
      tags: ["Angular", "Typescript"],
      images: [],
      latestUpdate: new Date(2024, 5, 28),
    },
    {
      id: 7,
      title: "Money Project",
      shortdescription:"",
      description: "I made this python program to keep track of how much money do i have, it looks up the actual conversion rates and keeps track of my expenditures and income",
      image: "assets/projects/mon.png",
      link:'',
      maintag: "Program",
      tags: ["Python"],
      images: [],
      latestUpdate: new Date(2023, 5, 1),
    },
    {
      id: 8,
      title: "Plane game 2",
      shortdescription:"",
      description: "This is a simple game I made as a project in high school, we had to use the not very well known programming language, Pascal",
      image: "assets/projects/pg2-1.PNG",
      link:'',
      maintag: "Game",
      tags: ["Pascal"],
      images: ['assets/projects/pg2-1.PNG','assets/projects/pg2-2.PNG','assets/projects/pg2-3.PNG'],
      latestUpdate: new Date(2021, 4, 26),
    },
    {
      id: 9,
      title: "24 hour clock",
      shortdescription:"",
      description: "This is a 24 hour clock made in assembly, it is actually not as complicated as it seems",
      image: "assets/projects/assem.png",
      link:'',
      maintag: "Program",
      tags: ["Assembly","Keil uVision5","Proteus"],
      images: ["assets/projects/assem.png","assets/projects/prote.png"],
      latestUpdate: new Date(2024, 0, 21),
    },
    {
      id: 10,
      title: "Syncretic Project 1",
      shortdescription:"",
      description: "Control and regulation of temperature with an arduino board, the menu is located in the board itself, I utilized a PID regulator",
      image: "assets/projects/ps1.png",
      link:'',
      maintag: "Circuit",
      tags: ["C++","Arduino"],
      images: [],
      latestUpdate: new Date(2024, 0, 11),
    },
    {
      id: 11,
      title: "Website with database",
      shortdescription:"",
      description: "Very simple website made with php, which makes operations on a database",
      image: "assets/projects/pai-1.png",
      link:'',
      maintag: "Web",
      tags: ["php","SQL"],
      images: ["assets/projects/pai-1.png","assets/projects/pai-2.png","assets/projects/pai-3.png"],
      latestUpdate: new Date(2023, 11, 13),
    },
    {
      id: 12,
      title: "License Plate recognition",
      shortdescription:"",
      description: "This program,  with the help of the yolo and easyocr libraries, first it finds on an image the area where a license plate coul be located, and then it reads the letters and symbols from that area",
      image: "assets/projects/lpr.PNG",
      link:'',
      maintag: "Program",
      tags: ["Python","EasyOCR","YOLO"],
      images: [],
      latestUpdate: new Date(2023, 4, 15),
    },
    {
      id: 13,
      title: "Cake Maker",
      shortdescription:"",
      description: "This was my first OOP project, its not much but it was a valuable experience",
      image: "assets/projects/cm-2.png",
      link:'',
      maintag: "Program",
      tags: ["C++","OOP"],
      images: ["assets/projects/cm-2.png","assets/projects/cm-3.png"],
      latestUpdate: new Date(2022, 11, 23),
    },
    {
      id: 14,
      title: "3D engine",
      shortdescription:"",
      description: "To be honest I didnt make this project but I plan to develop my own 3d raycast engine, I still included here because I gained a lot by even making it work on my own PC",
      image: "assets/projects/3d.png",
      link:'https://www.youtube.com/watch?v=fSjc8vLMg8c',
      maintag: "Program",
      tags: ["C","SDL2"],
      images: [],
      latestUpdate: new Date(2024, 5, 5),
    }
  ];

  getAllProjects(){
    return this.projectList;
  }

  getProjectById(id: number): Observable<any> {
    const project = this.projectList.find(project => project.id === id);
    return of(project);
  }
}
