[build]
  publish = "dist/cvprojectapp"
  functions = "functions" # Optional, if you're using serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define headers to allow Netlify forms
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[headers]]
  # Enable caching for certain file types
  for = "/assets/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
